extends:
  - airbnb
  - prettier
  - prettier/react
  - plugin:prettier/recommended
  - eslint-config-prettier
parser: babel-eslint
rules:
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
  react/prefer-stateless-function:
    - 1
    - ignorePureComponents: true
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      printWidth: 100
  react/prop-types: off
  react/forbid-prop-types": off
  react/require-default-props: off
  react/default-props-match-prop-types: off
  react/no-unused-prop-types: off
  no-unused-vars: 0
  no-param-reassign: 0
  no-console: 0
  no-use-before-define: 0
  no-nested-ternary: 0
  no-underscore-dangle: 0
  no-constant-condition: 0
  global-require: 0
  react/no-array-index-key: off
  react/no-unescaped-entities: off
  react/destructuring-assignment: off
  react/jsx-props-no-spreading: off
  react/state-in-constructor: off
  react/no-danger: off
plugins:
  - prettier
